[workspace]
members = [
	"fluxer_admin",
	"fluxer_app_proxy",
	"fluxer_common",
	"fluxer_media_proxy",
	"fluxer_gifs",
	"fluxer_svc",
	"fluxer_messages",
	"fluxer_snowflakes",
	"tools/ci",
	"tools/dev",
	"tools/i18n_auto",
	"fluxer_users",
	"fluxer_unfurl",
	"packages/markdown_parser/rust",
]
exclude = [
	"packages/markdown_parser/rust/fuzz",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "AGPL-3.0-or-later"

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"
