// SPDX-License-Identifier: AGPL-3.0-or-later

import type {ApiContext} from '@app/api/ApiContext';
import type {AdminService} from '@app/api/admin/AdminService';
import type {AdminApiKeyService} from '@app/api/admin/services/AdminApiKeyService';
import type {AdminArchiveService} from '@app/api/admin/services/AdminArchiveService';
import type {AuthRequestService} from '@app/api/auth/AuthRequestService';
import type {DesktopHandoffService} from '@app/api/auth/services/DesktopHandoffService';
import type {SsoService} from '@app/api/auth/services/SsoService';
import type {ApplicationID, UserID} from '@app/api/BrandedTypes';
import type {IBlueskyOAuthService} from '@app/api/bluesky/IBlueskyOAuthService';
import type {IChannelRepository} from '@app/api/channel/IChannelRepository';
import type {ChannelRequestService} from '@app/api/channel/services/ChannelRequestService';
import type {ChannelService} from '@app/api/channel/services/ChannelService';
import type {MessageRequestService} from '@app/api/channel/services/message/MessageRequestService';
import type {StreamPreviewService} from '@app/api/channel/services/StreamPreviewService';
import type {StreamService} from '@app/api/channel/services/StreamService';
import type {ConnectionRequestService} from '@app/api/connection/ConnectionRequestService';
import type {ConnectionService} from '@app/api/connection/ConnectionService';
import type {NcmecSubmissionService} from '@app/api/csam/NcmecSubmissionService';
import type {DonationService} from '@app/api/donation/DonationService';
import type {FavoriteMemeRequestService} from '@app/api/favorite_meme/FavoriteMemeRequestService';
import type {FavoriteMemeService} from '@app/api/favorite_meme/FavoriteMemeService';
import type {GatewayRequestService} from '@app/api/gateway/GatewayRequestService';
import type {GifService} from '@app/api/gif/GifService';
import type {IGuildDiscoveryService} from '@app/api/guild/services/GuildDiscoveryService';
import type {GuildService} from '@app/api/guild/services/GuildService';
import type {EmbedService} from '@app/api/infrastructure/EmbedService';
import type {EntityAssetService} from '@app/api/infrastructure/EntityAssetService';
import type {ErrorI18nService} from '@app/api/infrastructure/ErrorI18nService';
import type {IGatewayService} from '@app/api/infrastructure/IGatewayService';
import type {IMediaService} from '@app/api/infrastructure/IMediaService';
import type {ISnowflakeService} from '@app/api/infrastructure/ISnowflakeService';
import type {IStorageService} from '@app/api/infrastructure/IStorageService';
import type {KVActivityTracker} from '@app/api/infrastructure/KVActivityTracker';
import type {LiveKitWebhookService} from '@app/api/infrastructure/LiveKitWebhookService';
import type {UserCacheService} from '@app/api/infrastructure/UserCacheService';
import type {InstanceConfigRepository} from '@app/api/instance/InstanceConfigRepository';
import type {SingleCommunityService} from '@app/api/instance/SingleCommunityService';
import type {InviteRequestService} from '@app/api/invite/InviteRequestService';
import type {InviteService} from '@app/api/invite/InviteService';
import type {LimitConfigService} from '@app/api/limits/LimitConfigService';
import type {RequestCache} from '@app/api/middleware/RequestCacheMiddleware';
import type {OpenAPIRouteMetadata} from '@app/api/middleware/ResponseTypeMiddleware';
import type {AuthSession} from '@app/api/models/AuthSession';
import type {User} from '@app/api/models/User';
import type {ApplicationService} from '@app/api/oauth/ApplicationService';
import type {BotAuthService} from '@app/api/oauth/BotAuthService';
import type {OAuth2ApplicationsRequestService} from '@app/api/oauth/OAuth2ApplicationsRequestService';
import type {OAuth2RequestService} from '@app/api/oauth/OAuth2RequestService';
import type {OAuth2Service} from '@app/api/oauth/OAuth2Service';
import type {IApplicationRepository} from '@app/api/oauth/repositories/IApplicationRepository';
import type {IOAuth2TokenRepository} from '@app/api/oauth/repositories/IOAuth2TokenRepository';
import type {ReadStateRequestService} from '@app/api/read_state/ReadStateRequestService';
import type {ReadStateService} from '@app/api/read_state/ReadStateService';
import type {ReportRequestService} from '@app/api/report/ReportRequestService';
import type {ReportService} from '@app/api/report/ReportService';
import type {RpcService} from '@app/api/rpc/RpcService';
import type {SearchService} from '@app/api/search/SearchService';
import type {StripeService} from '@app/api/stripe/StripeService';
import type {AgeVerificationService} from '@app/api/stripe/services/AgeVerificationService';
import type {ThemeService} from '@app/api/theme/ThemeService';
import type {EntranceSoundPlayService} from '@app/api/user/entrance_sound/EntranceSoundPlayService';
import type {EntranceSoundService} from '@app/api/user/entrance_sound/EntranceSoundService';
import type {IUserRepository} from '@app/api/user/IUserRepository';
import type {EmailChangeService} from '@app/api/user/services/EmailChangeService';
import type {MfaBackupCodesChallengeService} from '@app/api/user/services/MfaBackupCodesChallengeService';
import type {PasswordChangeService} from '@app/api/user/services/PasswordChangeService';
import type {UserAccountRequestService} from '@app/api/user/services/UserAccountRequestService';
import type {UserActivityBuffer} from '@app/api/user/services/UserActivityBuffer';
import type {UserAuthRequestService} from '@app/api/user/services/UserAuthRequestService';
import type {UserChannelRequestService} from '@app/api/user/services/UserChannelRequestService';
import type {UserContactChangeLogService} from '@app/api/user/services/UserContactChangeLogService';
import type {UserContentRequestService} from '@app/api/user/services/UserContentRequestService';
import type {UserRelationshipRequestService} from '@app/api/user/services/UserRelationshipRequestService';
import type {UserService} from '@app/api/user/services/UserService';
import type {ClientIpResolution} from '@app/api/utils/RequestClientIp';
import type {SweegoWebhookService} from '@app/api/webhook/SweegoWebhookService';
import type {WebhookRequestService} from '@app/api/webhook/WebhookRequestService';
import type {WebhookService} from '@app/api/webhook/WebhookService';
import type {WorkerTaskName} from '@app/api/worker/WorkerLaneConfig';
import type {ICacheService} from '@pkgs/cache/src/ICacheService';
import type {IEmailService} from '@pkgs/email/src/IEmailService';
import type {IRateLimitService} from '@pkgs/rate_limit/src/IRateLimitService';
import type {IWorkerService} from '@pkgs/worker/src/contracts/IWorkerService';
import type {Hono} from 'hono';
import type {ZodType} from 'zod';

export interface HonoEnv {
	Variables: {
		apiContext: ApiContext;
		user: User;
		requestId?: string;
		clientIpResolution?: ClientIpResolution;
		responseSchema: ZodType | null;
		openapiMetadata?: OpenAPIRouteMetadata;
		adminService: AdminService;
		adminArchiveService: AdminArchiveService;
		adminApiKeyService: AdminApiKeyService;
		adminApiKey?: {
			keyId: bigint;
			createdById: UserID;
		};
		adminApiKeyAcls: Set<string> | null;
		adminUserId: UserID;
		adminUserAcls: Set<string>;
		authTokenType?: 'session' | 'bearer' | 'bot' | 'admin_api_key';
		authViaCookie?: boolean;
		authToken?: string;
		authUserId?: string;
		oauthBearerAllowed?: boolean;
		oauthBearerToken?: string;
		oauthBearerApplicationId?: ApplicationID;
		oauthBearerScopes?: Set<string>;
		oauthBearerUserId?: UserID;
		auditLogReason: string | null;
		authRequestService: AuthRequestService;
		ssoService: SsoService;
		authSession: AuthSession;
		desktopHandoffService: DesktopHandoffService;
		cacheService: ICacheService;
		channelService: ChannelService;
		channelRequestService: ChannelRequestService;
		messageRequestService: MessageRequestService;
		channelRepository: IChannelRepository;
		connectionService: ConnectionService;
		connectionRequestService: ConnectionRequestService;
		blueskyOAuthService: IBlueskyOAuthService;
		donationService: DonationService;
		streamPreviewService: StreamPreviewService;
		streamService: StreamService;
		emailService: IEmailService;
		emailChangeService: EmailChangeService;
		mfaBackupCodesChallengeService: MfaBackupCodesChallengeService;
		passwordChangeService: PasswordChangeService;
		embedService: EmbedService;
		entityAssetService: EntityAssetService;
		entranceSoundService: EntranceSoundService;
		entranceSoundPlayService: EntranceSoundPlayService;
		favoriteMemeService: FavoriteMemeService;
		favoriteMemeRequestService: FavoriteMemeRequestService;
		gatewayService: IGatewayService;
		gatewayRequestService: GatewayRequestService;
		discoveryService: IGuildDiscoveryService;
		guildService: GuildService;
		inviteService: InviteService;
		inviteRequestService: InviteRequestService;
		liveKitWebhookService?: LiveKitWebhookService;
		mediaService: IMediaService;
		rateLimitService: IRateLimitService;
		readStateService: ReadStateService;
		readStateRequestService: ReadStateRequestService;
		kvActivityTracker: KVActivityTracker;
		userActivityBuffer: UserActivityBuffer;
		reportService: ReportService;
		reportRequestService: ReportRequestService;
		contactChangeLogService: UserContactChangeLogService;
		ncmecSubmissionService: NcmecSubmissionService;
		requestCache: RequestCache;
		rpcService: RpcService;
		searchService: SearchService;
		snowflakeService: ISnowflakeService;
		storageService: IStorageService;
		gifService: GifService;
		themeService: ThemeService;
		userCacheService: UserCacheService;
		userRepository: IUserRepository;
		userService: UserService;
		userAccountRequestService: UserAccountRequestService;
		userAuthRequestService: UserAuthRequestService;
		userChannelRequestService: UserChannelRequestService;
		userContentRequestService: UserContentRequestService;
		userRelationshipRequestService: UserRelationshipRequestService;
		sweegoWebhookService: SweegoWebhookService;
		webhookService: WebhookService;
		webhookRequestService: WebhookRequestService;
		workerService: IWorkerService<WorkerTaskName>;
		stripeService: StripeService;
		ageVerificationService: AgeVerificationService;
		applicationService: ApplicationService;
		oauth2Service: OAuth2Service;
		oauth2RequestService: OAuth2RequestService;
		oauth2ApplicationsRequestService: OAuth2ApplicationsRequestService;
		applicationRepository: IApplicationRepository;
		oauth2TokenRepository: IOAuth2TokenRepository;
		botAuthService: BotAuthService;
		sudoModeValid: boolean;
		sudoModeToken: string | null;
		instanceConfigRepository: InstanceConfigRepository;
		singleCommunityService: SingleCommunityService;
		limitConfigService: LimitConfigService;
		requestLocale: string;
		errorI18nService: ErrorI18nService;
		channelUpdateType?: number;
	};
}

export type HonoApp = Hono<HonoEnv>;
