[package]
name = "libfluxcore"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "=0.2.128"
zstd = {version = "0.14.0", default-features = false, features = ["no_asm", "thin", "wasm"]}

[dev-dependencies]
proptest = "1.11.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true

[workspace]
