apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.headlessName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway.labels" (dict "root" . "name" "gateway" "component" "discovery") | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  - name: epmd
    port: 4369
    protocol: TCP
    targetPort: epmd
  - name: erl-dist
    port: 8081
    protocol: TCP
    targetPort: erl-dist
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: fluxer
